##############################################
#     Make file of OV8850 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/ov8850/
EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_OV8850) += ov8850.o

#################### END #####################
