##############################################
#     Make file of S5K4H5YX_SAMSUNGEM camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/media/video/hik3/capture/s5k4h5yx_samsungem/
#EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HIK3_CAMERA_S5K4H5YX_SAMSUNGEM) += s5k4h5yx_samsungem.o

#################### END #####################
